accounts/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

posts/urls.py
from django.conf.urls import url, re_path
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^$', views.PostList.as_view(), name='all'),
    url(r'new/$', views.CreatePost.as_view(), name='create'),
    url(r'by/(?P<username>[-\w]+)', views.UserPosts.as_view(), name='for_user'),
    url(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(), name='single'),
    re_path(r'delete/(?P<pk>\d+)/$', views.DeletePost.as_view(), name='delete'),
]

simplesocial/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include, re_path
#from django.urls import url , include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name= 'home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/',include('django.contrib.auth.urls')),
    re_path(r'^test/$',views.TestPage.as_view(), name='test'),
    url(r'^posts/',include('posts.urls',namespace='posts')),
    url(r'^groups',include('groups.urls',namespace='groups')),
    re_path(r'^thanks/$',views.ThanksPage.as_view(), name='thanks'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Social Stars</title
      <!-- Latest compiled and minified CSS -->

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">

  <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">
  </head>
  <body>
    <nav class="navbar-mynav" role="navigation" id="navbar">
      <div class="container">
        <a class='navbar-brand mynav' href="{% url 'home' %}">Star Social</a>
        <ul class='nav navbar-nav navbar-right'>
          {% if user.is_authenticated %}
            <li><a href="{% url 'posts:create' %}">Posts</a></li>
            <li><a href="{% url 'groups:all' %}">Groups</a></li>
            <li><a href="{% url 'groups:create' %}">Create Group</a></li>
            <li><a href="{% url 'accounts:logout' %}">Log Out</a></li>
          {% else %}
            <li><a href="{% url 'groups:all' %}">Groups</a></li>
            <li><a href="{% url 'accounts:login' %}">Log In</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    <div class="container mycontent">
      {% block content %}

      {% endblock %}
    </div>
    <canvas id="canvas"></canvas>

    <script src="{% static "simplesocial/js/master.js"%}" type="text/javascript" ></script>

   <!-- Latest compiled and minified jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
  <h1> Welcome to Social Stars! </h1>
{% endblock %}

templates/test.html
{% extends 'base.html' %}
{% block content %}
  <h1>You are Now Logged In</h1>
{% endblock %}

templates/thanks.html
{% extends 'base.html' %}
{% block content %}
  <h1>Thanks for Visiting to us, Come back soon!!</h1>
{% endblock %}